### PR TITLE
viTVMode access macros + bugfixes

### LINKED ISSUE #376: Launch Title starts NTSC channels at 480i on PAL Wii
**Describe the bug**
On a PAL Wii set to output 480p in system settings (and correctly outputting 480p on the system menu), launching an NTSC N64 channel via Priiloader Launch Title can start it at 480i. In my case, this happened with a Super Mario 64 romhack called Usamune.

This problem is mitigated by setting only the video mode to NTSC via Anyregion Changer, on an otherwise PAL-configured Wii.

**Version**
0.10.0

**Expected behaviour**
The channel should start at 480p as per the system menu setting.

### PR DESCRIPTION
**Pull request by pyorot**
A fix related to [libogc video_types.h](https://libogc.devkitpro.org/video__types_8h.html). Thruout the code, the whole of `GXRModeObj.viTVMode` was being erroneously compared to `VI_NTSC`, which is a VI_TVMODE_FMT rather than a full VI_TVMode. This patch adds two macros to invert the `VI_TVMODE(fmt, mode)` transformation and recover the FMT and the MODE (this should be upstreamed to libogc), and then applies the macros thruout the codebase. The changes are pretty much:
1. `rmode->viTVMode == VI_NTSC` → `VI_TVMODE_FMT(rmode->viTVMode) == VI_NTSC` (bugfix)
2. `rmode->viTVMode & VI_NON_INTERLACE` → `VI_TVMODE_MODE(rmode->viTVMode) == VI_NON_INTERLACE` (code readability; old code relied on hack that `VI_NON_INTERLACE` was the only enum out of three that was odd).

Consequently, `VideoRegionMatches` now works, so mismatched regions will actually call `ShutdownVideo()` in the title loading codepath, which fixes #376.

([finally](https://youtu.be/-hUIp3eUyKI?t=247))

The second commit in this patchset just fixes a compiler warning by replacing a switch(bool) with an if-else.

Both commits tested by loading NTSC-U VC Super Mario 64 on a PAL Wii in 480p. However, there are a couple of bugs to look out for:
1. Now, the video takes a few more seconds to initialise and misses more of the intro of SM64.
2. The names of the titles are all still showing up as ????????, which I think is a regression on the master branch.

My old attempt at fixing #376 is at #378, but it'll probably remain a draft since I don't have the means to test the other changes.
- ~~Currently it still boots NTSC-U SM64 at 480i but I believe the mistake is that I replaced the `ShutdownVideo()` call with `SetVideoModeForTitle` rather than just adding the latter~~ (edit: nvm lol, `SetVideoModeForTitle` actually switches it from 480p to 480i 🤦‍♂️).
- The code indicates the rather alarming bug that cross-region discs will get forced into interlaced tho, which is an obstacle to replacing GeckoOS with Priiloader for general-purpose speedrunning (I'm doing all this to streamline recommended setups).
- It also just seems handicapped in a few other ways, like say that the memory edit to set VI mode is `videoMode > SYS_VIDEO_NTSC ? 0x00000001 : 0x00000000;` rather than `VI_TVMODE_FMT(rmode->viTVMode)`.

### CODE REVIEW

**Comment by pyorot** [comment]
^ actually sorry yeah i wanted to submit this readability patch as well, also tested in the same way as the others

File: src/Shared/Video.h [hunk 1]
```diff
@@ -26,6 +26,10 @@ Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 extern GXRModeObj *rmode;
 extern void *xfb;
 
+// upstream these macros into libogc imo to complement VI_TVMODE (https://libogc.devkitpro.org/video__types_8h.html)
```
Comment (DacoTaco) [inline src/Shared/Video.h:29]: * put #ifdef's around these so that when they are upstreamed they don't cause a conflict.
* add an include to `video__types.h` as i might be adding them there if this works.
* add a Vi_TVMODE_HASFMT which does the == , which i will add too if this works, and use it for comparisons. same with the mode define

File: src/priiloader/source/titles.cpp [hunk 2]
```diff
@@ -653,7 +644,7 @@ s32 LoadListTitles( void )
 			ClearScreen();
 			PrintFormat( 1, ((rmode->viWidth /2)-((strlen("Loading title..."))*13/2))>>1, 208, "Loading title...");
 
-			//lets start this bitch
+			//lets start this bitch // TODO: split out into LaunchTitle()
```
Comment (DacoTaco) [inline src/priiloader/source/titles.cpp:647]: no need to add todo, just split it :)

**Review by DacoTaco — CHANGES_REQUESTED** [review]

**Comment by pyorot** [comment]
> so this is tested? are you getting 480p now in SM64?
yes, thanks for the patience

> im getting confused because of all the PR's and comments tbh lol.
each commit is a change that'll either fix something or be turned into a comment justifying something that looks wrong in the code, so that it doesn't get inadvertently changed later. this pr has finished changes and the other one has stuff that needs testing or further explanation, yet i don't have the equipment or knowledge myself. for example, i asked for more info on `SYS_SET_VIDEO` in one of the review threads

 > also, the ?? name is, again, because priiloader is loaded without the right nand access. if you install it, and hold reset, it should show the title names. its not a regression and is pure because of access rights.
in both cases, the user should be told this (i patched ios 36 cos i was told to for example). but also, i checked just now and am getting ??s on installed priiloader no matter what i do, so there's something else missing i think

File: src/priiloader/source/titles.cpp (hunk 2 above)
Comment (pyorot) [reply src/priiloader/source/titles.cpp:647]: i held off cos i was unsure about the error handling, but i wouldn't mind doing a bit more refactoring so will post another commit for this later, as long as the 3 in this pr are approved as a first step

File: src/Shared/Video.h (hunk 1 above)
Comment (pyorot) [reply src/Shared/Video.h:29]: will do; on the third bullet, could you please explain which syntax you want exactly and why you prefer it to just using ==?

File: src/priiloader/source/titles.cpp (hunk 2 above)
Comment (DacoTaco) [reply src/priiloader/source/titles.cpp:647]: in that case, ill do the refactoring, and use exceptions like i do in the other code.

**Comment by DacoTaco** [comment]
> in both cases, the user should be told this (i patched ios 36 cos i was told to for example). but also, i checked just now and am getting ??s on installed priiloader no matter what i do, so there's something else missing i think
but priiloader doesn't use IOS36 unless its the installer and it was started without the flag for HBC to not reload IOS (aka, you were missing the meta.xml). 

the installed version should work, unless the content is moved to SD. i'd suggest looking into the priiloader log to see why it failed to read the title name

File: src/Shared/Video.h (hunk 1 above)
Comment (DacoTaco) [reply src/Shared/Video.h:29]: just easier to read imo, `if(HasFormat(videoMode, mode))` is just easier to read to me :D

Comment (pyorot) [reply src/Shared/Video.h:29]: that's fair yeah. also, `video_types.h` isn't included anywhere in the codebase so may not be necessary; wdyt?

Comment (DacoTaco) [reply src/Shared/Video.h:29]: not right now, no. but i will be putting the defines there :)

**Comment by DacoTaco** [comment]
> > the installed version should work, unless the content is moved to SD. i'd suggest looking into the priiloader log to see why it failed to read the title name
> 
> where is this log?
if you enable it in the settings, it logs to the primary external device (SD or USB)

File: src/Shared/Video.h (hunk 1 above)
Comment (DacoTaco) [reply src/Shared/Video.h:29]: ye, maybe do `IS`. HAS is more if multiple are possible like in a list or something

**Comment by pyorot** [comment]
> > > the installed version should work, unless the content is moved to SD. i'd suggest looking into the priiloader log to see why it failed to read the title name
> > 
> > 
> > where is this log?
> 
> if you enable it in the settings, it logs to the primary external device (SD or USB)

oh lol, i thought i needed a usb gecko and was print-debugging with PRINT_FORMAT 👌. i'll get back to this ?? issue later

**Comment by pyorot** [comment]
all tested (same way) and ready to go. prii.log isn't appearing on my usb drive unfort. my sd broke today while working on this, bit of plastic flew off and the wii ain't havin it anymore lol

**Comment by pyorot** [comment]
> is the setting enabled that dumps the debug log to file?

yeah, “dump gecko output” or similarly named

**Comment by DacoTaco** [comment]
i have setup my development environments (serial connection, obs, devkitPPC/libogc) on my new system and will be testing some stuff tomorrow :)

**Review by DacoTaco — APPROVED** [review]
